### PR TITLE
Merge basho/rebar3_cuttlefish:develop

### PR DESCRIPTION
**Pull request by aef-**
This is essentially https://github.com/vernemq/rebar3_cuttlefish/pull/37 with additional updates and commit history from Basho's version. I'm happy to reconcile changes between this and #37 if we're able to get #37 merged in.

### CODE REVIEW

**Comment by ioolkos** [comment]
@aef- Thanks! I'm not against merging history in. (but have not yet looked at the commits)
It absolutely must not break the VerneMQ release builds, though! :smile:  As an example, Verne does currently not use the extended_bin_script.

**Comment by aef-** [comment]
Thanks ioolkos, I gotcha! I diff'd the generated `bin scripts` with both versions and there isn't a difference. This is because you all are using `template` overlay without `generate_start_script`. I think, then, line 97 is the only difference, as the rest are essentially behind flags that are disabled by default so they should not affect your output. Let me know, I'll make w/e changes necessary to get this merged in.

**Comment by ioolkos** [comment]
@aef- Thanks. I just run a local build test for Verne, with your `rebar3_cuttlefish` PR in a `_checkouts` dir, so that the plugin is taken locally from there. Seems it does not break nodetool/vernemq/vmq-admin scripts, so looks good so far.

**Comment by ioolkos** [comment]
@aef- I'm merging this, somewhat guerilla style. It doesn't seem to break Verne builds but my thinking is that the merge will surface any issues with that rather quickly, in any case.

**Comment by aef-** [comment]
Sounds good @ioolkos!

**Pull request merged**
